### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Corbynx010** [itz-d0dgy/NTLMv1-To-NTLM#1]
Just a couple of quick suggestions that could improve this tool:
- Ideally there would be a flag to output the DES keys in password cracker formats e.g. `--hashcat` or `--john`
- Make it explicitly clear that there is a specific key 1 and key 2 and these can not get confused or this tool will not work
- The command output in the text document refers to an earlier version name of this tool `ntlm_multi_d0dgy_rewrite.py` and should be changes to `ntlmv1-to-ntlm.py`:
`python3 ntlm_multi_d0dgy_rewrite.py --stitch --cracked_des_key_1 X --cracked_des_key_2 X --ntlm_challenge_type_3 X --ntlm_challenge X`

**Comment by itz-d0dgy** [comment]
Thanks @Corbynx010, ill take a look at implementing these suggestions 🙂

**Comment by itz-d0dgy** [comment]
>     * Ideally there would be a flag to output the DES keys in password cracker formats e.g. `--hashcat` or `--john`
I will  add flags for `--hashcat` and `--hashtopolis`, unsure if john supports the equivalent of hashcats `-m 14000`

>     * Make it explicitly clear that there is a specific key 1 and key 2 and these can not get confused or this tool will not work
Thoughts on console output message: `[!] PLEASE BE AWARE THE DES KEY FILE HAS THE KEYS ORDERED AND WHEN CRACKED THE ORDER MUST BE MAINTAINED :)`

>     * The command output in the text document refers to an earlier version name of this tool `ntlm_multi_d0dgy_rewrite.py` and should be changes to `ntlmv1-to-ntlm.py`:
>       `python3 ntlm_multi_d0dgy_rewrite.py --stitch --cracked_des_key_1 X --cracked_des_key_2 X --ntlm_challenge_type_3 X --ntlm_challenge X`

Good catch 😅

**Comment by itz-d0dgy** [comment]
Changes implemented based on feedback
